version: '3'

services:
  db:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .//sqlite3:/root/db/
    ports:
      - '9000:9000'
    restart: unless-stopped

  backend:
    image: vish29/sd-backend
    container_name: API
    depends_on:
    - db
    ports:
     - '8000:8000'
    environment:
      - DATABASE_URL = sqlite:///main.db
  
  frontend:
    image: vish29/sd-client
    container_name: Client
    ports:
      - '3000:3000'

    depends_on:
      - backend
    stdin_open: true

